# Generated by Django 4.2.20 on 2025-05-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
