# Generated by Django 4.2.20 on 2025-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0003_participant_is_event_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram', null=True, unique=True),
        ),
    ]
