# Generated by Django 4.2.20 on 2025-05-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0004_speaker_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
    ]
