# Generated by Django 4.2.20 on 2025-05-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0005_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
