# Generated by Django 4.2.20 on 2025-05-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0006_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
