# Generated by Django 4.2.20 on 2025-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0007_alter_speaker_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан'),
        ),
        migrations.AddField(
            model_name='participant',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='events_bot.event', verbose_name='Зарегистрированные мероприятия'),
        ),
    ]
