# Generated by Django 4.2.20 on 2025-05-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0008_participant_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запрос на знакомство', 'verbose_name_plural': 'Запросы на знакомство'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Донат', 'verbose_name_plural': 'Донаты'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'Спикер', 'verbose_name_plural': 'Спикеры'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Временной слот', 'verbose_name_plural': 'Временные слоты'},
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='events_bot.participant', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='target_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='events_bot.participant', verbose_name='Целевой участник'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время запроса'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='events_bot.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждён'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='events_bot.participant', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время доната'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='bio',
            field=models.TextField(blank=True, help_text='Короткая информация о роде деятельности', null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_event_manager',
            field=models.BooleanField(default=False, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на рассылку'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='question',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events_bot.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Ответ получен'),
        ),
        migrations.AlterField(
            model_name='question',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events_bot.participant', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='question',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events_bot.speaker', verbose_name='Спикер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='speakers', to='events_bot.event', verbose_name='Мероприятия'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='ID пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание доклада'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='events_bot.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='events_bot.speaker', verbose_name='Спикер'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название доклада'),
        ),
    ]
