# Generated by Django 4.2.20 on 2025-05-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0009_alter_connectionrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_extended',
            field=models.BooleanField(default=False, help_text='Если отмечено, спикер будет считаться текущим вне зависимости от расписания', verbose_name='Выступление продлено'),
        ),
    ]
