# Generated by Django 4.2.20 on 2025-05-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_bot', '0011_participant_is_first_in_networking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='notified_about_newcommers',
            new_name='notified_about_newcomers',
        ),
    ]
